mongo:
    image: mongo:5.0.28
    ports:
      - "27017:27017"
    restart: always
    # Eliminamos el healthcheck por ahora para que no bloquee la API
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=hermod
    volumes:
      - ./mongodb/data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  api:
    # ... resto de tu config ...
    depends_on:
      - mongo # Sin la condición de healthy para que arranque sí o sí
